package com.lacoders.textclassification.dao.model;

import java.util.Date;

public class CommentPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.news_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Date commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.news_id
     *
     * @return the value of comment.news_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.news_id
     *
     * @param newsId the value for comment.news_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_time
     *
     * @return the value of comment.comment_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_time
     *
     * @param commentTime the value for comment.comment_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.deleted
     *
     * @return the value of comment.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.deleted
     *
     * @param deleted the value for comment.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_content
     *
     * @return the value of comment.comment_content
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_content
     *
     * @param commentContent the value for comment.comment_content
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}