package com.lacoders.textclassification.dao.model;

import java.util.Date;

public class NewsPO {

    private Integer newsId;

    private String newsSrc;

    private String newsTitle;

    private String newsType;

    private String newsWriter;

    private Date newsTime;

    private Integer deleted;

    private String maintext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_src
     *
     * @return the value of news.news_src
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public String getNewsSrc() {
        return newsSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_src
     *
     * @param newsSrc the value for news.news_src
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setNewsSrc(String newsSrc) {
        this.newsSrc = newsSrc == null ? null : newsSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_type
     *
     * @return the value of news.news_type
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public String getNewsType() {
        return newsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_type
     *
     * @param newsType the value for news.news_type
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setNewsType(String newsType) {
        this.newsType = newsType == null ? null : newsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_writer
     *
     * @return the value of news.news_writer
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public String getNewsWriter() {
        return newsWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_writer
     *
     * @param newsWriter the value for news.news_writer
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setNewsWriter(String newsWriter) {
        this.newsWriter = newsWriter == null ? null : newsWriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_time
     *
     * @return the value of news.news_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Date getNewsTime() {
        return newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_time
     *
     * @param newsTime the value for news.news_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setNewsTime(Date newsTime) {
        this.newsTime = newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.deleted
     *
     * @return the value of news.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.deleted
     *
     * @param deleted the value for news.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.maintext
     *
     * @return the value of news.maintext
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public String getMaintext() {
        return maintext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.maintext
     *
     * @param maintext the value for news.maintext
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setMaintext(String maintext) {
        this.maintext = maintext == null ? null : maintext.trim();
    }
}