package com.lacoders.textclassification.dao.model;

import java.util.Date;

public class UserTokenPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.user_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.creat_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.level
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.user_id
     *
     * @return the value of user_token.user_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.user_id
     *
     * @param userId the value for user_token.user_id
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.token
     *
     * @return the value of user_token.token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.token
     *
     * @param token the value for user_token.token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.creat_time
     *
     * @return the value of user_token.creat_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.creat_time
     *
     * @param creatTime the value for user_token.creat_time
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.level
     *
     * @return the value of user_token.level
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.level
     *
     * @param level the value for user_token.level
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.deleted
     *
     * @return the value of user_token.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.deleted
     *
     * @param deleted the value for user_token.deleted
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}