package com.lacoders.textclassification.dao.mapper;

import com.lacoders.textclassification.dao.model.CommentPO;
import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int insert(CommentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    CommentPO selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    List<CommentPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int updateByPrimaryKey(CommentPO record);
}