package com.lacoders.textclassification.dao.mapper;

import com.lacoders.textclassification.dao.model.UserPO;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int insert(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    UserPO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    List<UserPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int updateByPrimaryKey(UserPO record);
}