package com.lacoders.textclassification.dao.mapper;

import com.lacoders.textclassification.dao.model.UserTokenPO;
import java.util.List;

public interface UserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int insert(UserTokenPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    UserTokenPO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    List<UserTokenPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Mon Feb 28 11:05:52 CST 2022
     */
    int updateByPrimaryKey(UserTokenPO record);
}